name: Build MATI Cross-Platform

on:
  push:
    branches: [ "main" ] # Se activa automáticamente al hacer merge a main
  workflow_dispatch:     # Mantiene el botón manual por si las dudas

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Descargar el código
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar dependencias de sistema (Solo Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgirepository1.0-dev gcc libcairo2-dev pkg-config python3-dev gir1.2-gtk-3.0 libwebkit2gtk-4.1-0

    - name: Instalar librerías de Python
      run: |
        pip install pyinstaller pywebview
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          pip install PyGObject==3.48.2
        fi
      shell: bash

    - name: Compilar ejecutable (Windows)
      if: matrix.os == 'windows-latest'
      # Fíjate cómo en Windows usamos punto y coma (;) para separar las carpetas
      run: |
        pyinstaller --windowed --onefile --name "MATI" --add-data "frontend;frontend" --add-data "core;core" --add-data "rcs;rcs" --add-data "assets;assets" main.py

    - name: Compilar ejecutable (Linux y Mac)
      if: matrix.os != 'windows-latest'
      # En Mac/Linux usamos dos puntos (:) para separar las carpetas
      run: |
        pyinstaller --windowed --onefile --name "MATI" --add-data "frontend:frontend" --add-data "core:core" --add-data "rcs:rcs" --add-data "assets:assets" --hidden-import gi --hidden-import gi.repository.Gtk --hidden-import gi.repository.Gdk --hidden-import gi.repository.WebKit2 main.py

    - name: Guardar Artifacts (Descargables)
      uses: actions/upload-artifact@v4
      with:
        name: MATI-${{ matrix.os }}
        path: dist/
