name: Build and Public Release

on:
  push:
    tags:
      - 'v*' # Se activa al subir tags como v1.1.1
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install pyinstaller pywebview
      
      - name: Build Windows
        if: matrix.os == 'windows-latest'
        run: pyinstaller --windowed --onefile --name "MATI" --add-data "frontend;frontend" --add-data "core;core" main.py
        
      - name: Build Mac
        if: matrix.os == 'macos-latest'
        run: pyinstaller --windowed --name "MATI" --add-data "frontend:frontend" --add-data "core:core" main.py

      - name: Zip Mac App
        if: matrix.os == 'macos-latest'
        run: cd dist && zip -r MATI-macOS.zip MATI.app

      - name: Upload to Public Release
        uses: softprops/action-gh-release@v2
        with:
          # SUSTITUYE con tu usuario y el nombre del repo público
          repository: alejandro/MATI-Releases 
          token: ${{ secrets.RELEASE_TOKEN }}
          files: |
            dist/MATI.exe
            dist/MATI-macOS.zip
